### ISSUE TITLE
Liftover for CNA data

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#196]
### Description:

As a PDXFinder user, I want all the CNA data to be at the same assembly so that I can easily use it for my needs.

### Acceptance criteria:

- [x] all CNA data is updated to GRCh38

**Comment by Afollet** [comment]
Did not complete in previous sprint.  Current method of lifting CNA still results in heavy data loss due to coordinates being marked as "deleted in new assembly"

This happens heavily in NKI and UOC-BC datasets. I will need to experiment with turning off fidelity on the liftOver process for CNA data.

Curie-LC CNA data is not formatted correctly and does not run as is (low complexity fix)
CLR data is not currently being read because of the nested file structure (low complexity fix)

**Comment by Afollet** [comment]
CNA data exists in the following UPDOG directories:

./NKI/cna - 366 dropped out of 255865 data points 
./UOC-BC/cna - WGS - Many dropped data points after lift - 228601 dropped out of 867163
./Curie-LC/cna - Capable of lifting, however yet to attempt

./PMLB/cna - No genomic coordinates - no assembly
./IRCC-GC/cna - No genomic coordinates - hg19

./CRL/cna - No genomic coordinates -- already on GRCh38
./IRCC-CRC/cna - Wes is Hg38 - targeted NGS has no assembly and no genomic coordinates

**Comment by zperova** [comment]
is taking longer than expected because of the differences in datasets

**Comment by Mandloi2309** [comment]
done

**Comment by Mandloi2309** [comment]
./CRL/cna: 228385 not lifted out of 21276110 = 1.07%
./PIVOT/cna: 28224 not lifted out of 8126244 = 0.32%
./PMLB/cna:  100864 not lifted out of 5698304 = 1.7%
./IRCC-GC/cna: 3180 not lifted out of 14989 = 21%
./LIH/cna: lifted all data points to GRCh38
./Curie-LC/cna: 495 not lifted out of 89585 = 0.5%
