### ISSUE TITLE
Remove column labels in empty columns in templates

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#264]
## Description:

To reproduce:
Open Curie-BC_metadata-sample.tsv file and look for the empty columns after all the ones with data.
The headers copy the name of the column.

### Acceptance criteria:

- [x] headers from the empty columns removed
- [x] templates are updated

**Comment by Afollet** [comment]
The empty column problem exists not only in Curie-BC_metadata-sample.tsv sporadically throughout the repository. I believe .xlsx to .tsv digestion pipeline is causing it which is ran by executing the file ./generate_tsv.bash. This bug needs to be investigated and fixed in the pipeline if that is where it is originating.

**Comment by zperova** [comment]
Tushar to update templates once on the EBI machine

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
this is something useful to implement as results in templates having large number of empty columns and thus larger files and might cause problems with the ETL. 
@Mandloi2309 will look into raw data to determine whether this is for one particular provider or more widespread, and if so what is the reason for this.

**Comment by Mandloi2309** [comment]
done
