### ISSUE TITLE
Download function is not working

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#852]
**Describe the bug**
Download function is not working.

**To Reproduce**
1. Go to https://www.pdxfinder.org/data/pdx/SJCRH/SJEWS001321_X1#patients
2. Click on Download PDF
3. See blank page

**Expected behavior**
A file is downloaded

**Desktop (please complete the following information):**
 - OS Big Sur
 - Browser Chrome
 - Version 97.0.4692.71 (Official Build) (x86_64)

Also tried in firefox - same behaviour

**Comment by mauroz77** [comment]
The error was due to fields that were null (in this specific case: Race / Ethnicity). Java generates the input for a javascript library to create the pdf but because of the null values the input was not the expected one by the library.

Solution:
To change null values for an empty string, so the library can process the information correctly.

**Comment by zperova** [comment]
Thank you @mauroz77 for sorting this out quickly. I wonder why this has not been picked up by the validator? Doesn't it assign Not provided/Not specified where values are absent?

**Comment by mauroz77** [comment]
@zperova good point. At least _Not provided_ is the value it shows in the web page (before exporting to pdf), so somehow that value is lost when processing the data to be sent to the pdf library. Should we move this ticket back to "in progress"?

**Comment by mauroz77** [comment]
@zperova The change to show ethnicity instead of race when exporting to pdf is ready. Moving this to done
